/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenesUserDonationsRouteImport } from './routes/scenes/user-donations'
import { Route as ScenesTopDonationRouteImport } from './routes/scenes/top-donation'
import { Route as ScenesTextRouteImport } from './routes/scenes/text'
import { Route as ScenesLatestDonationRouteImport } from './routes/scenes/latest-donation'

const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesUserDonationsRoute = ScenesUserDonationsRouteImport.update({
  id: '/user-donations',
  path: '/user-donations',
  getParentRoute: () => ScenesRoute,
} as any)
const ScenesTopDonationRoute = ScenesTopDonationRouteImport.update({
  id: '/top-donation',
  path: '/top-donation',
  getParentRoute: () => ScenesRoute,
} as any)
const ScenesTextRoute = ScenesTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => ScenesRoute,
} as any)
const ScenesLatestDonationRoute = ScenesLatestDonationRouteImport.update({
  id: '/latest-donation',
  path: '/latest-donation',
  getParentRoute: () => ScenesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scenes': typeof ScenesRouteWithChildren
  '/scenes/latest-donation': typeof ScenesLatestDonationRoute
  '/scenes/text': typeof ScenesTextRoute
  '/scenes/top-donation': typeof ScenesTopDonationRoute
  '/scenes/user-donations': typeof ScenesUserDonationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scenes': typeof ScenesRouteWithChildren
  '/scenes/latest-donation': typeof ScenesLatestDonationRoute
  '/scenes/text': typeof ScenesTextRoute
  '/scenes/top-donation': typeof ScenesTopDonationRoute
  '/scenes/user-donations': typeof ScenesUserDonationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scenes': typeof ScenesRouteWithChildren
  '/scenes/latest-donation': typeof ScenesLatestDonationRoute
  '/scenes/text': typeof ScenesTextRoute
  '/scenes/top-donation': typeof ScenesTopDonationRoute
  '/scenes/user-donations': typeof ScenesUserDonationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scenes'
    | '/scenes/latest-donation'
    | '/scenes/text'
    | '/scenes/top-donation'
    | '/scenes/user-donations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scenes'
    | '/scenes/latest-donation'
    | '/scenes/text'
    | '/scenes/top-donation'
    | '/scenes/user-donations'
  id:
    | '__root__'
    | '/'
    | '/scenes'
    | '/scenes/latest-donation'
    | '/scenes/text'
    | '/scenes/top-donation'
    | '/scenes/user-donations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScenesRoute: typeof ScenesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes/user-donations': {
      id: '/scenes/user-donations'
      path: '/user-donations'
      fullPath: '/scenes/user-donations'
      preLoaderRoute: typeof ScenesUserDonationsRouteImport
      parentRoute: typeof ScenesRoute
    }
    '/scenes/top-donation': {
      id: '/scenes/top-donation'
      path: '/top-donation'
      fullPath: '/scenes/top-donation'
      preLoaderRoute: typeof ScenesTopDonationRouteImport
      parentRoute: typeof ScenesRoute
    }
    '/scenes/text': {
      id: '/scenes/text'
      path: '/text'
      fullPath: '/scenes/text'
      preLoaderRoute: typeof ScenesTextRouteImport
      parentRoute: typeof ScenesRoute
    }
    '/scenes/latest-donation': {
      id: '/scenes/latest-donation'
      path: '/latest-donation'
      fullPath: '/scenes/latest-donation'
      preLoaderRoute: typeof ScenesLatestDonationRouteImport
      parentRoute: typeof ScenesRoute
    }
  }
}

interface ScenesRouteChildren {
  ScenesLatestDonationRoute: typeof ScenesLatestDonationRoute
  ScenesTextRoute: typeof ScenesTextRoute
  ScenesTopDonationRoute: typeof ScenesTopDonationRoute
  ScenesUserDonationsRoute: typeof ScenesUserDonationsRoute
}

const ScenesRouteChildren: ScenesRouteChildren = {
  ScenesLatestDonationRoute: ScenesLatestDonationRoute,
  ScenesTextRoute: ScenesTextRoute,
  ScenesTopDonationRoute: ScenesTopDonationRoute,
  ScenesUserDonationsRoute: ScenesUserDonationsRoute,
}

const ScenesRouteWithChildren =
  ScenesRoute._addFileChildren(ScenesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScenesRoute: ScenesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
